id: https://hotecosystem.org/tccm/resolvedvalueset
name: resolvedvalueset
title: Resolved Value Set
license: https://creativecommons.org/publicdomain/zero/1.0/
description: >-
  ValueSet definitions can be resolved dynamically on an as needed basis, but they also can be transferred between
  systems without the necessity of maintaining complete copies of the code system versions that are used to resolve
  them. This model defines the output of a value set resolution request. It contains sufficient information that the
  request can be completely reproduced against a service instance the mirrors the state of the system doing the
  resolution. It also carries the result of the resolution that can be transferred and loaded into a system that does
  not mirror the source system state.

prefixes:
  tccm: https://hotecosystem.org/tccm/
  biolinkml: https://w3id.org/biolink/biolinkml/

default_prefix: tccm
default_range: string

classes:
  ResolvedValueSetHeader:
    description: The information required to completely resolve a value set definition.
    slot_usage:
      resolutionOf:
        description: The specific value set definition that was resolved
        range: ValueSetDefinitionReference
        optional: true
      resolvedUsingCodeSystem:
        description: A reference to a code system version that was used in the resolution of this value set definition.
        range: CodeSystemVersionReference
        mutivalued: true
      includesResolvedValueSet:
        description: >-
          If the value set includes other value sets, this contains the resolution information used to resolve the
          inner value sets.
        range: ResolvedValueSetHeader
        multivalued: true

  ResolvedValueSet:
